### ISSUE TITLE
Shapecaster getPointOnRay not exposed

### ISSUE THREAD

**Issue by DennisSmolek** [jrouwe/JoltPhysics.js#154]
When trying to write a Shapecaster I got to the point where I'd need to check the casting position and realized that the `getPointOnRay` is not exposed in the idl

[getPointOnRay Method](https://jrouwe.github.io/JoltPhysics/struct_shape_cast_t.html#a90dcaf5d1e22122cf08862b9da811c96)

Without it there's no way to determine where in space the result happens. 

I haven't messed with the IDL yet but the project readme said I can also submit a ticket.

**Comment by LeXXik** [comment]
Your hit result will contain `mFraction`, which is a float. You can simply multiply your normalized ray direction with it to get the hit point in space.

**Comment by DennisSmolek** [comment]
> Your hit result will contain `mFraction`, which is a float. You can simply multiply your normalized ray direction with it to get the hit point in space.

Doesnt the shapecast have an end point based on the direction? Thats why its a fraction and not a distance?

**Comment by jrouwe** [comment]
ShapeCast::GetPointOnRay is implemented as:

`mCenterOfMassStart.GetTranslation() + inFraction * mDirection;`

so the calculation is pretty trivial (and all the properties are public).

**Comment by jrouwe** [comment]
Fixed in #155

**Comment by DennisSmolek** [comment]
> ShapeCast::GetPointOnRay is implemented as:
> 
> `mCenterOfMassStart.GetTranslation() + inFraction * mDirection;`
> 
> so the calculation is pretty trivial (and all the properties are public).

So "Fraction" isn't the percentage between the origin and destination, but a pure distance value?

if the origin is `[0,0,0]` and the direction is `[0,0,300]` with a intersection in the very center.

With "Fraction" I thought the value would be `0.5` for 50% 

But because it's a distance function the actual value would be `150`. 

Is that correct?

**Comment by jrouwe** [comment]
The answer is: It depends.

Normally if you do a CastShape call, you'll specify an 'early out' fraction on the collision collector. By default this is 1.0 + the smallest possible number so that the result > 1.0. This means you'll receive hits between in the range [0, 1], so effectively `mDirection` is the length of your cast and 0.5 means 50% along the length of the cast. However, you're totally free to normalize mDirection and set the early out fraction to e.g. 100, now your cast is 100 meters long and mFraction 10 would mean 10 meter from the start.
