### ISSUE TITLE
ESpringMode.StiffnessAndDamping spring is always hard

### ISSUE THREAD

**Issue by kutu** [jrouwe/JoltPhysics.js#66]
after changing `mSuspensionSpring.mMode` to `StiffnessAndDamping` spring is always hard
no matter what values i put into `mSuspensionSpring.mStiffness` or `mSuspensionSpring.mFrequency` (i tried values from 0 to 10000)

`mSuspensionSpring.HasStiffness()` method is not available

**Comment by jrouwe** [comment]
The value is ```Jolt.ESpringMode_StiffnessAndDamping```, did you use that?

I can expose the HasStiffness function.

**Comment by jrouwe** [comment]
I adjusted the example and it seems to work for me:

[vehicle_wheeled.zip](https://github.com/jrouwe/JoltPhysics.js/files/13527553/vehicle_wheeled.zip)

My guess is that your stiffness is not high enough and that your vehicle is hitting the suspension hardpoint (mSuspensionMinLength) because the suspension is too weak.

Assuming here that all force ends up on 1 wheel, which is not true, but this is just to get a ballpark value:

```
force = stiffness * delta_spring_length = vehicle_mass * gravity
````

In the example, the vehicle weighs 1500 kg and I've changed the length of the spring so it goes from 1.0 - 2.0. This means you need a stiffness in the order of:

```
stiffness = vehicle_mass * gravity / delta_spring_length = 1500 * 10 / 1 = 15000
```

for the spring to be powerful enough.

**Comment by kutu** [comment]
shame on me
i have only tried 10000 value, now i set 20000 and it works
my apology

maybe put that information in here https://jrouwe.github.io/JoltPhysics/class_spring_settings.html#a688815c0e85518f1ac42f1d077415472

because when using freq and damping, values are low 0-2

**Comment by jrouwe** [comment]
> maybe put that information in here

Done.

**Comment by jrouwe** [comment]
Also HasStiffness is now exposed.

**Comment by LeXXik** [comment]
Funny I was implementing constraints just now and wanted to say there is an example how to calculate an approximate stiffness. It looks like the example appeared because of this isse. Good timing :D
